# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 24d54e480dd58574bd78956711602c8eaad7a2b0432c83e1913813c6617e5d18796a8f7a23d6fd0da78bc3649d8ea345acb0903c786028d11e91b3e501399d2e

test:
  secret_key_base: 9974312e8df0c7a8fbd2675b23f1896e4f10ba6eb408ebb1480669e7c222acf37f8047809609eccf0a61ed84bf712162db2d7f14d40a7876944c8fb313b31d70

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
